name: "Default"
description: "General purpose — tasks, vitals, git, energy."
color: bright_cyan
refresh: 15
left_ratio: 2
right_ratio: 3

layout:
  left:
    - focus
    - energy
    - loops
  right:
    - vitals
    - git
